use_default_settings: true

general:
  instance_name: "OtsX"
  debug: false
  donation_url: false
  contact_url: false
  enable_metrics: true

brand:
  issue_url: ""
  docs_url: ""
  public_instances: ""
  wiki_url: ""
  custom:
    links: {}

server:
  public_instance: false
  limiter: false
  image_proxy: false

ui:
  default_theme: simple
  results_on_new_tab: false
  query_in_title: false
  infinite_scroll: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json 