name: otsXng
services:
  - name: searxng
    source_dir: /
    dockerfile_path: otsx/Dockerfile
    github:
      repo: puunukk/searxng
      branch: master
    environment_slug: basic-xxs
    instance_count: 1
    envs:
      - key: SEARXNG_SETTINGS_PATH
        value: $SEARXNG_SETTINGS_PATH
      - key: SEARXNG_SECRET
        value: $SEARXNG_SECRET
    http_port: 8080
